### ISSUE TITLE
ImportError: No module named signals

### ISSUE THREAD

**Issue by philippeluickx** [jezdez/django-configurations#100]
Hey!

I am trying to get Celery up and running. It worked fine before migrating to django-configurations.
However, getting hit with a "no module named signals" error.
Not sure if this is related to
- celery
- configurations
- haystack (which pops up in the stacktrace)

```python
from __future__ import unicode_literals
from __future__ import absolute_import

# Python imports
import os

# Django imports
from django.conf import settings

# Contrib imports
from celery import Celery
from configurations import (
    values,
    importer,
)

# Project imports


# set the default Django settings module for the 'celery' program.
os.environ.setdefault(
    'DJANGO_SETTINGS_MODULE',
    'my_project.config'
)
os.environ.setdefault(
    'DJANGO_CONFIGURATION',
    'Local',
)

importer.install()

app = Celery(
    'my_project',
    broker='amqp://',
    backend='amqp://',
    include=['apps.profiles.tasks'],
)

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)


@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

<pre>
Traceback (most recent call last):
  File "/home/my_project/.virtualenvs/my_project/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/base.py", line 270, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/fixups/django.py", line 69, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/celery/fixups/django.py", line 154, in validate_models
    django_setup()
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/haystack/__init__.py", line 52, in <module>
    signal_processor_class = loading.import_class(signal_processor_path)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 22, in import_class
    module_itself = importlib.import_module(module_path)
  File "/home/my_project/.virtualenvs/my_project/local/lib/python2.7/site-packages/django/utils/importlib.py", line 49, in import_module
    __import__(name)
ImportError: No module named signals
</pre>

**Comment by philippeluickx** [comment]
So found the culprit:

HAYSTACK_SIGNAL_PROCESSOR = 'signals.MyProjectSignalProcessor'

When I prefix this with my projects name, then celery moves to the next issue (in my case installed apps) where I need to prefix as well to have celery stop complaining
>> HAYSTACK_SIGNAL_PROCESSOR = 'my_project.signals.OravaSignalProcessor'

But then of course I can not do *runserver* anymore...

Is this a django-configurations issue or celery? Not an expert, but guessing that something goes wrong on the level on which imports are done.

**Comment by philippeluickx** [comment]
Figured out this is more a mess of how different packages handle imports. Not really related to django-configurations, thus closing the issue.
