### ISSUE TITLE
LaxOptionParser removed from Django 1.8

### ISSUE THREAD

**Issue by powellc** [jezdez/django-configurations#106]
Just upgraded my project to Django 1.8 and ran into:

```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from configurations.management import execute_from_command_line
  File "/home/powellc/projects/plownow/venv/local/lib/python2.7/site-packages/configurations/management.py", line 1, in <module>
    from . import importer
  File "/home/powellc/projects/plownow/venv/local/lib/python2.7/site-packages/configurations/importer.py", line 8, in <module>
    from django.core.management import LaxOptionParser
ImportError: cannot import name LaxOptionParser
```

**Comment by powellc** [comment]
Oops, I'm an idiot ... should search through closed tickets first:

https://github.com/jezdez/django-configurations/issues/65

Thanks for a great library :smile:
